[package]
name = "gogo_shogi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
once_cell = "1.8.0"
getopts = "0.2"

[profile.release]
debug = 1
